In [ ]:
import pandas as pd

In [5]:
import joblib

# Load the feature selector
feature_selector = joblib.load(r"C:\Users\User\Downloads\selected_features.pkl")

# Check what type of object it is
print(type(feature_selector))

# Print the contents to understand its structure
print(feature_selector)

<class 'list'>
['age', 'population_weight', 'mobile_money_registered', 'savings_mobile_banking', 'debit_card', 'savings_secret_place', 'loan_goods_credit', 'formal_savings_score', 'informal_savings_score', 'digital_financial_score', 'formal_credit_score', 'informal_credit_score', 'financial_product_diversity', 'formal_financial_score', 'informal_financial_score', 'financial_engagement_score', 'product_category_diversity', 'risk_management_score', 'gender_female', 'gender_male', 'education_level_primary', 'education_level_secondary', 'education_level_unknown', 'residence_type_rural', 'residence_type_urban', 'marital_status_divorced/separated', 'marital_status_married/living with partner', 'marital_status_single', 'marital_status_widowed', 'relationship_to_hh_head', 'relationship_to_hh_other relative', 'relationship_to_hh_parent', 'relationship_to_hh_son/daughter', 'relationship_to_hh_spouse', 'region_central', 'region_central rift', 'region_coast', 'region_lower eastern', 'region_mid eastern', 'region_north eastern', 'region_upper eastern', 'formal_informal_ratio_Formal_Only', 'formal_informal_ratio_Informal_Only', 'formal_informal_ratio_Mixed', 'formal_informal_ratio_None', 'credit_to_savings_ratio_Mixed', 'credit_to_savings_ratio_None', 'credit_to_savings_ratio_Savings_Only']

In [ ]:
# Load your dataset (replace with actual file path)
df = pd.read_csv("your_data.csv")

# Get dataset columns
dataset_features = df.columns.tolist()

# Check if all selected features exist in the dataset
missing_features = [feature for feature in selected_features if feature not in dataset_features]

if missing_features:
    print("Missing features:", missing_features)
else:
    print("All selected features are present in the dataset.")

In [3]:
import pandas as pd

df = pd.read_csv(r"D:\Django\material-dashboard-django-master\2016_data.csv", on_bad_lines="skip")

df.shape  # Check how many rows were loaded

(8208, 51)

In [4]:
df.iloc[8200:8210]

,respondent_id,age,gender,education_level,residence_type,marital_status,relationship_to_hh,region,population_weight,mobile_money_registered,...,insurance_livestock,insurance_nhif,insurance_health_other,insurance_life,insurance_education,insurance_other,pension_nssf,pension_mbao,pension_other,financially_excluded
8200,23151664,36.0,male,secondary,urban,married/living with partner,head,nyanza,4542.83400,yes,...,no,yes,no,no,no,no,no,no,no,no
8201,23148250,37.0,male,primary,rural,divorced/separated,head,nyanza,1466.62010,yes,...,no,yes,no,no,no,no,no,no,no,no
8202,22902257,24.0,female,tertiary,urban,single,head,nyanza,1363.24100,yes,...,no,yes,no,no,no,no,no,no,no,no
8203,22706687,28.0,female,secondary,urban,married/living with partner,spouse,nyanza,774.16000,yes,...,no,no,no,no,no,no,no,no,no,no
8204,23538836,30.0,female,secondary,urban,divorced/separated,head,nyanza,1763.37020,yes,...,no,no,no,no,no,no,no,no,no,no
8205,23533373,35.0,male,primary,urban,married/living with partner,head,nyanza,237.86922,yes,...,no,no,no,no,no,no,no,no,no,no
8206,22559735,35.0,female,tertiary,rural,married/living with partner,head,nyanza,565.14910,yes,...,no,yes,no,no,no,no,yes,no,yes,no
8207,23892905,23.0,female,secondary,rural,married/living with partner,spouse,nyanza,5247.89060,yes,...,no,yes,no,no,no,no,no,no,no,no

In [5]:
missing_values = df.isnull().sum()
missing_values

respondent_id               0
age                         0
gender                      0
education_level             0
residence_type              0
marital_status              0
relationship_to_hh          0
region                      0
population_weight           0
mobile_money_registered     0
savings_mobile_banking      0
bank_account_current        0
bank_account_savings        0
bank_account_everyday       0
postbank_account            0
bank_overdraft              0
debit_card                  0
credit_card                 0
savings_microfinance        0
savings_sacco               0
savings_group_friends       0
savings_family_friend       0
savings_secret_place        0
loan_bank                   0
loan_mobile_banking         0
loan_sacco                  0
loan_microfinance           0
loan_shylock                0
loan_group_chama            0
loan_govt                   0
loan_employer               0
loan_family_friend          0
loan_shopkeeper_cash        0
loan_goods_credit           0
loan_digital_app            0
loan_agri_buyer_supplier    0
loan_hire_purchase          0
loan_mortgage               0
insurance_motor             0
insurance_home              0
insurance_crop              0
insurance_livestock         0
insurance_nhif              0
insurance_health_other      0
insurance_life              0
insurance_education         0
insurance_other             0
pension_nssf                0
pension_mbao                0
pension_other               0
financially_excluded        0
dtype: int64